databases:
  - name: mapapp_database
    databaseName: mapapp_database
    user: mapapp
    region: singapore

services:
  - type: web
    name: mapapp
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mapapp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
